[package]
name = "vrp-pragmatic"
version = "1.2.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.2.0" }

serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"

chrono = "0.4.11"
rand = "0.7.3"

[dev-dependencies]
proptest = "0.9.6"
uuid = { version = "0.8.1", features = ["v4"] }
